name: PickupBuddingAmethyst
version: '1.21.1-0'
main: me.truedarklord.pickupBuddingAmethyst.PickupBuddingAmethyst
api-version: '1.21'
authors: [ TrueDarkLord ]
description: Lets you pick up budding amethysts.
